### ISSUE TITLE
Problem parsing list of repos when Create or CreateOrUpdate

### ISSUE THREAD

**Issue by lilyjma** [AlexGhiondea/ghcreate#8]
![image](https://user-images.githubusercontent.com/25314976/85349045-3be0fb80-b4b2-11ea-817b-afbc27cd24d2.png)

Labels can't be created successfully, but can be if do it one repo at a time.

**Comment by AlexGhiondea** [comment]
I think this is because you have a `,` in there. Can you try removing the `,`?
